Support for IPython %magics, like %timeit
cansarigol/pdbr pull request #28
Opened 2022-02-06 18:41 UTC by giladbarnea

Hi, thanks for pdbr!

Since IPython is already baked into RichPdb (if available), it itched me to unlock some IPython features, so I started with `%magic` commands.
This is something that I've wanted to do for some time now; pdbr stands for a lot of things I enjoy: terminal debuggers, `IPython` and `rich` library.

I've added 2 functions in `_pdbr.py`, wrote a test in `test_pdbr.py`, and added a description of the feature in the `README.md`. 

I had trouble testing the actual magic functionality, because when trying to init a `rich_pdb_klass(IPython.terminal.debugger.TerminalPdb)` inside a test, it raises an exception, complaining about stdout not being a terminal. I couldn't get past that.

Additionally, some magics don't work out of the box, for example `%lsmagic`. This can be fixed by overriding `onecmd()`, but I wanted to know if you're at all interested in this PR's idea before adding more changes. Let me know if you want this fixed as well :)

Thanks,
Gilad

2022-02-07 07:57 UTC, cansarigol requested changes
Great job @giladbarnea . I was planning to work on it especially for `%env` command. With your PR all magic will be real :). Thanks for your effort. 

Because of pytest `--pdb` is activated in project, you can see the real error via `-s` like `pytest tests/test_pdbr.py -s`. And you also need to put `ipython` package in test func of the `noxfile`.

2022-02-07 07:57 UTC, cansarigol commented on pdbr/_pdbr.py
> +                return result or ""
```suggestion
                return self._print(result) or ""
```
this change will fix some commands like `lsmagic`

2022-02-07 07:57 UTC, cansarigol commented on pdbr/_pdbr.py
> +            return result or ""
```suggestion
            return self._print(result) or ""
```

2022-02-07 08:03 UTC, cansarigol commented
@giladbarnea When i run a command and run magic secondly, i always see the last result with magic result. Can you have a look at it as well?

![Screenshot from 2022-02-07 09-02-37](https://user-images.githubusercontent.com/5008696/152748319-7b4bafc4-5a7f-4e03-a09c-6f0597a64665.png)

2022-02-07 09:48 UTC, giladbarnea commented
@cansarigol thanks for the quick reply :)
It looks like we're dealing with more than 1 issue, what do you think about writing tests for individual magics? I'd be happy to do it. There are a few dozen, I guess we'll find out we're not interested in some, or that others are working weirdly and require a more comprehensive fix. 

About that bug with the repeating output, maybe it has to do with `self.cmdqueue` in `pdb.Pdb.precmd()`, or `cmd.Cmd.emptyline()`. I'll have to check that.

By the way, maybe it's worth sharing, I've made a pseudocode gist of the main loop. It helps me sort out the inheritance / method overload mess (`cmd.Cmd > pdb.Pdb > IPython.core.debugger.Pdb > IPython.terminal.debugger.TerminalPdb > RichPdb`):
![image](https://user-images.githubusercontent.com/18548473/152764287-0e5d44da-eaa8-42f4-b63f-96bdc0ff2264.png)

Are there any magics that you don't want altogether?

2022-02-07 10:07 UTC, cansarigol commented
@giladbarnea  writing tests for individual magics and making out `TerminalPdb` class and overriding its `cmdloop` are great ideas, please go ahead. My only objection would be for the `%pdb` but I don't have too much experience with magics.

2022-02-26 12:23 UTC, cansarigol commented
Hi @giladbarnea your PR looks great 👍.  If you don't have time to put inherited TerminalPdb class, let's merge it as is and you can pursue with a new PR. Thanks for your effort btw

2022-02-26 12:36 UTC, giladbarnea commented
> Hi @giladbarnea your PR looks great +1. If you don't have time to put inherited TerminalPdb class, let's merge it as is and you can pursue with a new PR. Thanks for your effort btw

Hi, you're right, I couldn't find the time (had my first kid a week ago :))
Let me see what quick wins I can get us within the next 45 minutes, I'll prepare a good-enough commit and hopefully it'll be ok.

2022-02-26 16:36 UTC, cansarigol requested changes

2022-02-26 16:36 UTC, cansarigol commented on noxfile.py
> +        "IPython",
For the latest version of Ipython, there is a bug that is about to get reverted.
```suggestion
        "IPython==8.0.0",
```

2022-02-26 16:47 UTC, cansarigol commented
@giladbarnea tests fail for me. Are they same for you as well?

2022-02-26 18:26 UTC, giladbarnea commented
> @giladbarnea tests fail for me. Are they same for you as well?

@cansarigol Yes, I think at the very least the `session.install()` statement in `noxfile.test()` should include a `.` to install `pdbr` itself, and `session.run()` should include a `"--capture=no"` arg. 
This fixes some tests but others are still failing, I'll update when it's fixed

2022-02-26 22:20 UTC, giladbarnea commented
@cansarigol That's it, [f13020f](https://github.com/cansarigol/pdbr/pull/28/commits/f13020f72c15cd0671a679cecf17f77f1f8cc32c) succeeded through the CI pipeline.

2022-02-27 15:43 UTC, merged

2022-02-27 15:43 UTC, cansarigol commented
@giladbarnea Great, thanks for your effort again. I am looking forward to using it myself first :smiley_cat: 

we can fix windows test errors later.